#ifndef CONFIGFILE_H
#define CONFIGFILE_H

#define FRONT_ULTRASONIC 1
#define FRONT_ULTRASONIC_TR 2
#define FRONT_ULTRASONIC_EC 3

#define RIGHT_ULTRASONIC 0
#define RIGHT_ULTRASONIC_TR 0
#define RIGHT_ULTRASONIC_EC 0

#define LEFT_ULTRASONIC 0
#define LEFT_ULTRASONIC_TR 0
#define LEFT_ULTRASONIC_EC 0

#define LEFT_ENCODER 0
#define LEFT_ENCODER_PIN 0

#define RIGHT_ENCODER 0
#define RIGHT_ENCODER_PIN 0

#define FRONT_ULTRASHORTIR 0
#define FRONT_ULTRASHORTIR_PIN 0

#define LEFT_ULTRASHORTIR 0
#define LEFT_ULTRASHORTIR_PIN 0

#define RIGHT_ULTRASHORTIR 0
#define RIGHT_ULTRASHORTIR_PIN 0

#define BACK_ULTRASHORTIR 0
#define BACK_ULTRASHORTIR_PIN 0

#define GYROSCOPE 0


#endif // CONFIGFILE_H
