#ifndef CONFIGFILE_H
#define CONFIGFILE_H

//Motor definitions
#define MOTORS_OPPOSITE 1 //IF THE MOTORS ARE WIRED OPPOSITELY
//SWAP THE MOTOR_DIRECTIONS IF THE ROBOT IS GOING BACKWARDS
#define MOTOR_DIRECTION_BACK 1
#define MOTOR_DIRECTION_FRONT 0

#define RIGHT_WHEEL 1
#define RIGHT_WHEEL_PWM 1
#define RIGHT_WHEEL_DIR 9

#define LEFT_WHEEL 1
#define LEFT_WHEEL_PWM 0
#define LEFT_WHEEL_DIR 8


#define DIAMETER_WHEEL 0
#define DISTANCE_BETWEEN_WHEELS 0

//Define values for the motors
#define MAXIMUM_NORMALIZED_SAFE_SPEED_MOTORS 0.4
#define MAXIMUM_REVOLUTIONS_PER_SECOND 1
#define MAXIMUM_SPEED MAXIMUM_REVOLUTIONS_PER_SECOND
#define MAXIMUM_DEGREES_PER_SECOND 360
#define MAXIMUM_ANGULAR_SPEED MAXIMUM_DEGREES_PER_SECOND


//SENSORS
//Ultrasonic
#define FRONT_ULTRASONIC 0
#define FRONT_ULTRASONIC_TR 2
#define FRONT_ULTRASONIC_EC 3

#define RIGHT_ULTRASONIC 0
#define RIGHT_ULTRASONIC_TR 0
#define RIGHT_ULTRASONIC_EC 0

#define LEFT_ULTRASONIC 0
#define LEFT_ULTRASONIC_TR 0
#define LEFT_ULTRASONIC_EC 0


//Encoder
#define LEFT_ENCODER 1
#define LEFT_ENCODER_DIR LEFT_WHEEL_DIR
#define LEFT_ENCODER_ENC 4

#define RIGHT_ENCODER 1
#define RIGHT_ENCODER_DIR RIGHT_WHEEL_DIR
#define RIGHT_ENCODER_ENC 5


//UltrashortIR
#define FRONT_ULTRASHORTIR 0
#define FRONT_ULTRASHORTIR_PIN 0

#define LEFT_ULTRASHORTIR 0
#define LEFT_ULTRASHORTIR_PIN 0

#define RIGHT_ULTRASHORTIR 0
#define RIGHT_ULTRASHORTIR_PIN 0

#define BACK_ULTRASHORTIR 0
#define BACK_ULTRASHORTIR_PIN 0


//ShortIR
#define FRONT_SHORTIR 0
#define FRONT_SHORTIR_PIN 0

#define LEFT_SHORTIR 0
#define LEFT_SHORTIR_PIN 0

#define RIGHT_SHORTIR 0
#define RIGHT_SHORTIR_PIN 0

#define BACK_SHORTIR 0
#define BACK_SHORTIR_PIN 0

//Gyroscope
#define GYROSCOPE 1
#define GYROSCOPE_CHIP_PIN 10
#define GYROSCOPE_SPI_PIN 0
#define GYROSCOPE_CLOCKWISE_POSITIVE -1 //Change to -1 if it is negative in the clockwise direction



//Define values for the alpha parameter of the filter of the sensors
#define SHORT_IR_ALPHA 0.7
#define ULTRASHORT_IR_ALPHA 0.5
#define ULTRASONIC_ALPHA 0.7
#define ENCODER_ALPHA 0
#define GYROSCOPE_TOTAL_ALPHA 0.7
#define GYROSCOPE_READING_ALPHA 0.7




//Speed control
//Define gains for the speed control. safe between 0<GAIN<1
#define SPEED_CONTROL_UPDATE_RATE_MILISECONDS 50
#define FWD_SPEED_GAIN 4
#define ANG_SPEED_GAIN 4
#endif // CONFIGFILE_H
